### ISSUE TITLE
Error regarding Geometry Message

### ISSUE THREAD

**Issue by vedantdave97** [alanzjl/t3_release#1]
Hello @alanzjl 
Great Work!
I was facing issue while running pretrain.py:
```
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
```
Its from autolab_core that I already installed as per the installation file. I also tried installing it from source: https://berkeleyautomation.github.io/autolab_core/install/install.html#option-2-install-from-source-for-ros but that also does not work.
Does it have to do something with ROS? I also installed ros-humble-geometry-msgs. But that also does not work.
Thanks.

**Comment by alanzjl** [comment]
Hi @vedantdave97 thanks for your interest! Feel free to ignore those warnings - they are for ROS-related stuff however in this package `autolab-core` was only used for pose transformations, hence no ROS. If the script is failing it should be due to other reasons - what's the full terminal output and what's the command that you were running?

Alan

**Comment by vedantdave97** [comment]
Hello @alanzjl 

Thanks for the reply. That was just a warning. It was working.
Just one question: From what I can see, you provided a collab that contains pretrained model loading. Also the same is in the train_nn.py. Is there any script for pretraining as in the paper? Am I missing something?

Regards,
Vedant

**Comment by alanzjl** [comment]
Hi @vedantdave97 thanks for your interest! You are right that the colab only contains inference code that loads the pretrained models. However, the pretraining code is also in this repository. Checkout [here](https://github.com/alanzjl/t3/blob/341177f232df3b824a5246b0d1855cd9e4d2cf29/scripts/train_nn.py#L12),

```python
pretrainer = T3Pretrain(cfg)
pretrainer.setup_model()
pretrainer.setup_optimizer()
pretrainer.setup_dataset()
print("Dataset setup complete")
# pretrainer.train()
pretrainer.test(20, "", 0, False)
```

If you uncomment the `pretrainer.train()` line then feed in the proper data mixture then that's it for pretraining.
