### ISSUE TITLE
Publishing DIGIT encoder

### ISSUE THREAD

**Issue by joshwajones** [alanzjl/t3_release#2]
Hi @alanzjl, would it be possible to publish the DIGIT T3 encoder weights (corresponding to pretraining II, ideally tiny or small)? I don't see it anywhere on https://huggingface.co/datasets/alanz-mit/FoundationTactile/tree/main/models/t3_tiny/encoders, and I'd love to use it for a project I'm working on.

**Comment by alanzjl** [comment]
Hi @joshwajones! Sorry for the late response! I've uploaded the encoder weights from pretraining II, including the ones for the digit sensor in our hugging face page. Hope that's useful!
